version: "3.8"
services:
  nginx:
    container_name: tandemite-nginx
    image: nginx:latest
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    tty: true
    links:
      - php
  php:
    container_name: tandemite-php
    build: docker/php
    working_dir: /var/www/html
    volumes:
      - ./php:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/z-php.ini:/usr/local/etc/php/conf.d/z-php.ini:ro
      - ./docker/php/.bashrc:/root/.bashrc:ro
    tty: true
    depends_on:
      - db
      - db-test
  db:
    image: postgres:latest
    container_name: tandemite-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: tandemite
    ports:
      - 5432:5432
    volumes:
      - ./data/db-normal:/var/lib/postgresql/data
    tty: true
  db-test:
    image: postgres:latest
    container_name: tandemite-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: tandemite-test
    ports:
      - 5433:5432
    volumes:
      - ./data/db-test:/var/lib/postgresql/data
    tty: true
    depends_on:
      - db
  vite:
    container_name: tandemite-node
    build: docker/front
    ports:
      - "80:8000"
    working_dir: /srv/app
    volumes:
      - ./front:/srv/app
    tty: true
  