category_controllers:
    resource:
        path: ../src/Client/Application/
        namespace: App\Client\Application
    type: attribute
    prefix: /api/v1
    trailing_slash_on_root: false

user_controllers:
    resource:
        path: ../src/User/Application/
        namespace: App\User\Application
    type: attribute
    prefix: /api/v1
    trailing_slash_on_root: false

