category_controllers:
    resource:
        path: ../src/Client/Application/
        namespace: App\Client\Application
    type: attribute
    prefix: /api/v1/clients
    trailing_slash_on_root: false
